version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - 8081:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - kafka
    environment:
        SPRING_PROFILES_ACTIVE: "local"
        ALLOWED_ORIGINS: "*"
        ALLOWED_METHODS: "*"
        ALLOWED_HEADERS: "*"
        EXPOSED-HEADERS: "*"
    networks:
      - default
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
        - default
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: 'kafka'
    image: 'bitnami/kafka:latest'
    networks:
      - default
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - default
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9093"
    depends_on:
      - "kafka"

  prometheus:
    image: prom/prometheus:latest
    container_name: "monitoring-prometheus"

    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: "monitoring-grafana"

    depends_on:
      - prometheus
    links:
      - prometheus
    ports:
      - "3000:3000"


networks:
  default:
    name: restaurant-services
    external: true
