version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - 8081:8080
    depends_on:
      - kafka
    environment:
        SPRING_PROFILES_ACTIVE: "local"
        ALLOWED_ORIGINS: "*"
        ALLOWED_METHODS: "*"
        ALLOWED_HEADERS: "*"
        EXPOSED-HEADERS: "*"
    networks:
      - default
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
        - default
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: 'kafka'
    image: 'bitnami/kafka:latest'
    networks:
      - default
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

networks:
  default:
    name: restaurant-services
    external: true
